export const COLOURS = {
  white: '#ffffff',
  black: '#000000',
  lightGray: '#B3B4B6',
  accent: '#FFC231',
  accentRed: '#FB5D2E',
  accentPink: '#F96165',
};

export const Categories = [
  {
    name: 'Burger',
    image: require('../assets/foods/Barger.png'),
    items: [
      {
        name: 'Classic Burger',
        weight: 'Views: 4.2K',
        rating: '5.0',
        price: '80 L.E',
        isTopOfTheWeek: true,
        image: require('../database/images/burger/burger1.jpg'),
        size: 'Large 8"',
        crust: 'Single',
        delivery: 25,
        ingredients: [
          require('../database/images/burger/beef1.png'),

          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/burger/green.jpg'),
        ],
      },
      {
        name: 'Chicken Burger',
        weight: 'Views: 3.0K',
        rating: '4.5',
        price: '100 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/burger/burger2.jpg'),
        size: 'Large 12"',
        crust: 'Single',
        delivery: 30,
        ingredients: [
          require('../database/images/burger/beef2.jpg'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/Tomato.png'),

          require('../database/images/burger/green.jpg'),
        ],
      },
      {
        name: 'Cheese Burger',
        rating: ' 4.2',
        weight: 'Views: 2.8K',
        price: '120 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/burger/burger3.png'),
        size: 'Large 15"',
        crust: 'Double',
        delivery: 35,
        ingredients: [
          require('../database/images/burger/beaf.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/Sliced-Onion.png'),
          require('../database/images/burger/green.jpg'),
        ],
      },
    ],
  },
  {
    name: 'Pizza',
    image: require('../assets/foods/Pizza.png'),
    items: [
      {
        name: 'Pepperoni Pizza',
        weight: 'Views: 6.8 K',
        rating: '6.5',
        price: '120 L.E',
        isTopOfTheWeek: true,
        image: require('../database/images/pizza/pepperonipizza.png'),
        size: 'Large 14"',
        crust: 'Thin Crust',
        delivery: 30,
        ingredients: [
          require('../database/images/pizza/meet.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/pizza/sauce.png'),
        ],
      },
      {
        name: 'Cheese Pizza',
        weight: 'Views: 5.3 K',
        rating: '5.2',
        price: '155 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/plaincheesepizza.png'),
        size: 'Large 16"',
        crust: 'Thin Cheese',
        delivery: 25,
        ingredients: [
          require('../database/images/pizza/mcheese.png'),
          require('../database/images/cheese.png'),
          require('../database/images/pizza/cheese.png'),
          require('../database/images/pizza/pinable.png'),
        ],
      },
      {
        name: 'Mexican Green Wave',
        weight: 'Views: 4.1 K',
        rating: '5.0',
        price: '200 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/pizza/mexicangreenwave.png'),
        size: 'Large 18"',
        crust: 'Wavey',
        delivery: 45,
        ingredients: [
          require('../database/images/pizza/bacon.png'),
          require('../database/images/cheese.png'),
          require('../database/images/Tomato.png'),
          require('../database/images/pizza/olive.png'),
          require('../database/images/pizza/mushroom.png'),
          require('../database/images/pizza/pepper.png'),
        ],
      },
    ],
  },
  {
    name: 'Fried Chicken',
    image: require('../assets/foods/Fride.png'),
    items: [
      {
        name: 'Crispy Fried',
        weight: 'Views: 5.3 K',
        rating: '5.5',
        price: '95 L.E',
        isTopOfTheWeek: true,
        image: require('../database/images/fride/fride1.jpg'),
        size: 'Small Pices',
        crust: 'Crispy',
        delivery: 10,
        ingredients: [
          require('../database/images/fride/chiken meat.png'),
          require('../database/images/fride/p1.png'),
          require('../database/images/fride/p2.png'),
        ],
      },
      {
        name: 'Buffalo Wings',
        weight: 'Views: 5.1 K',
        rating: '5.0',
        price: '110 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/fride/fride2.jpg'),
        size: 'Medium Pices',
        crust: 'Grilled',
        delivery: 15,
        ingredients: [
          require('../database/images/fride/fresh-chicken.png'),
          require('../database/images/fride/p2.png'),
          require('../database/images/fride/p3.png'),
        ],
      },
      {
        name: 'Smoked Fride',
        weight: 'Views: 4.8 K',
        rating: '4.6',
        price: '130 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/fride/fride3.jpg'),
        size: 'Large Pices',
        crust: 'Smoked',
        delivery: 25,
        ingredients: [
          require('../database/images/fride/fresh-chicken2.png'),
          require('../database/images/fride/p2.png'),
          require('../database/images/fride/p3.png'),
          require('../database/images/fride/p4.png'),
        ],
      },
    ],
  },
  {
    name: 'Pasta',
    image: require('../assets/foods/pasta.png'),
    items: [
      {
        name: 'Spaghetti',
        weight: 'Views: 4.6 K',
        rating: '4.8',
        price: '75 L.E',
        isTopOfTheWeek: true,
        image: require('../database/images/pasta/spaghetti.png'),
        size: 'Medium Dish',
        crust: 'Spaghetti',
        delivery: 10,
        ingredients: [
          require('../database/images/pasta/s1.png'),
          require('../database/images/pasta/meat2.png'),
          require('../database/images/pasta/red sace.jpg'),
          require('../database/images/pasta/basil.png'),
        ],
      },
      {
        name: 'Italian White Sauce',
        weight: 'Views: 4.4 K',
        rating: '4.3',
        price: '100 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/pasta/italian.jpg'),
        size: 'Medium Dish',
        crust: 'Italian',
        delivery: 12,
        ingredients: [
          require('../database/images/pasta/s2.jpg'),
          require('../database/images/pasta/meat2.png'),
          require('../database/images/pasta/whitesauce.jpg'),
          require('../database/images/pasta/basil.png'),
        ],
      },
      {
        name: 'Ricette',
        weight: 'Views: 3.7 K',
        rating: '3.8',
        price: '130 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/pasta/ricette.jpg'),
        size: 'Medium Dish',
        crust: 'Italian',
        delivery: 30,
        ingredients: [
          require('../database/images/pasta/s3.jpg'),
          require('../database/images/pasta/meat2.png'),
          require('../database/images/pasta/red sace.jpg'),
          require('../database/images/fride/p2.png'),
        ],
      },
    ],
  },
  {
    name: 'Fish',
    image: require('../assets/foods/fish.png'),
    items: [
      {
        name: 'Fried Fish',
        weight: 'Views:5.0 K',
        rating: '5.0',
        price: '80 L.E',
        isTopOfTheWeek: true,
        image: require('../database/images/fish/fish1.jpg'),
        size: 'Medium',
        crust: 'Fried',
        delivery: 15,
        ingredients: [require('../database/images/fish/f1.jpg')],
      },
      {
        name: 'Grilled Fish',
        weight: 'Views:4.5 K',
        rating: '4.0',
        price: '120 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/fish/gfish.jpg'),
        size: 'Medium',
        crust: 'Grilled',
        delivery: 18,
        ingredients: [require('../database/images/fish/f2.jpg')],
      },
      {
        name: 'Fried Shrimp',
        weight: 'Views:4.4 K',
        rating: '4.1',
        price: '120 L.E',
        isTopOfTheWeek: false,
        image: require('../database/images/fish/fs.jpg'),
        size: 'Small',
        crust: 'Fried',
        delivery: 12,
        ingredients: [require('../database/images/fish/f3.jpg')],
      },
    ],
  },
];
